deployment:
  image: gcr.io/PROJECT_ID/IMAGE:TAG

namespace: cart-api-gcp-develop
name: cart-api-gcp

ConfigMap:
  name: authorization-config
  data: 
    ASPNETCORE_ENVIRONMENT: Development
    DD_ENV: core-local
    DD_SERVICE: DatadogContainerExample
    DD_VERSION: 1.0.0
    # DD_AGENT_HOST: datadog-agent
    # DD_TRACE_ROUTE_TEMPLATE_RESOURCE_NAMES_ENABLED: true
    # DD_RUNTIME_METRICS_ENABLED: true

Secret:
  name: authorization-secrets

replicaCount: 1
