# Datadog Agent with Logs, APM, Processes, and System Probe enabled

targetSystem: "linux"
datadog:
  apiKey: bec8189ee5154f324d8f692a6f050b94
  appKey: <DATADOG_APP_KEY>
  clusterName: autopilot-cluster-1-datadog

  # Enable the new `kubernetes_state_core` check.
  kubeStateMetricsCore:
    enabled: true
  # Avoid deploying kube-state-metrics chart.
  # The new `kubernetes_state_core` doesn't require to deploy the kube-state-metrics anymore.
  kubeStateMetricsEnabled: false

providers:
  gke:
    autopilot: true