targetSystem: linux

deployment:
  image: gcr.io/PROJECT_ID/IMAGE:TAG

namespace: cart-api-gcp-develop
name: cart-api-gcp

ConfigMap:
  name: authorization-config
  data: 
    ASPNETCORE_ENVIRONMENT: Development
    DD_ENV: core-local
    DD_SERVICE: DatadogContainerExample
    DD_VERSION: 1.0.0
    DD_AGENT_HOST: datadog-agent
    # DD_TRACE_ROUTE_TEMPLATE_RESOURCE_NAMES_ENABLED: "true"
    # DD_RUNTIME_METRICS_ENABLED: true
    DD_API_KEY: 98f42bda-6e7d-5f53-960e-f170be7ff27f
    DD_APM_ENABLED: true
    DD_APM_NON_LOCAL_TRAFFIC: true 
    DD_DOGSTATSD_NON_LOCAL_TRAFFIC: true

Secret:
  name: authorization-secrets

replicaCount: 1

datadog:
  ## @param apm - object - required
  ## Enabled apm agent and provide custom configs
  #
  apm:
    ## @param enabled - boolean - optional - default: false
    ## Enable this to enable APM and tracing, on port 8126
    #
    enabled: true
