apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.Secret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
type: Opaque
stringData:
  Messages__Message: "Method Reached!!!"